rly_file = "Bernina_Express_RhB.rly"
ttb_files = [ "RhB_BerninaPass_2020.ttb",]
ssn_files = []
country_code = "CH"
name = "Rhaetian Railway: Bernina Express"
description = "Depiction of the route between St. Moritz in Switzerland and Tirano in Italy"
display_name = "Bernina Express"
author = "Krizar"
img_files = [ "BerninaExpress.bmp",]
doc_files = [ "README.md",]
release_date = "2022-02-23"
version = "1.0.0"
factual = true
contributors = []
